#!/bin/bash

upper=`echo -n ${1:0:1} | tr [a-z] [A-Z]; echo ${1:1}`

cd /lisp/projects/new-project

if [ -d ../$1 ]; then 
    echo "Error: ../$1 already exists."
    exit -1
fi

mkdir ../$1
cp packages.lisp first.lisp new-sub-project.asd ../$1
find ../$1 -type f -exec sed -i "s/new-project/$1/g" {} \;
find ../$1 -type f -exec sed -i "s/New-Project/$upper/g" {} \;

mv ../$1/new-sub-project.asd ../$1/$1.asd
ln -s ../$1/$1.asd ../systems
