#!/bin/bash

output=`mktemp -u`
mkfifo $output

control="$HOME/.spaceship/${DISPLAY:1:1}/control"

base=`basename $0`

if [ $base = "spaceship-cmd" ]; then
    echo $1 $output $2 $3 $4 $5 $6 $7 >> $control
else
    echo $base $output $1 $2 $3 $4 $5 $6 >> $control
fi

rtn=`cat $output`
rm $output

if [ ${rtn:0:2} = "#!" ]; then
    eval "$rtn"
else
    echo "$rtn"
fi

