#!/bin/bash

base=`basename $0`

if [ $base = "spaceship-cmd-file" ]; then
    echo spaceship-cmd-file must be called through a symbolic link
    exit
fi

filename=`readlink -f "$1"`
escaped=${filename//\ /\\\ }

output=`mktemp -u`
mkfifo $output

control="$HOME/.spaceship/${DISPLAY:1:1}/control"

echo $base $output $escaped >> $control

cat $output
rm $output